name: GitHub Brach Trello

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: pmill/github-trello@v1.18
        with:
          trello-api-key: ${{ secrets.TRELLO_API_KEY }}
          trello-auth-token: ${{ secrets.TRELLO_AUTH_TOKEN }}
          trello-board-id: ${{ secrets.TRELLO_BOARD }}
